appo-dec-rock-sampling:
    env: envs.rock_sampling.rock_samling.DecRockSamplingEnv
    run: APPO
    stop:
        timesteps_total: 200000
    config:
        # Works for both torch and tf.
        framework: torch

        gamma: 0.99
        lr: 0.0001

        # 4-agent MA cartpole.
        env_config:
          config:
            num_agents: 4

        num_envs_per_worker: 5
        num_workers: 4
        num_gpus: 1
        _fake_gpus: true

        observation_filter: MeanStdFilter
        num_sgd_iter: 1
        vf_loss_coeff: 0.005
        vtrace: true
        model:
            fcnet_hiddens: [32]
            fcnet_activation: linear
            vf_share_layers: true

        multiagent:
            policies: ["pagent_0", "pagent_1"]
            # YAML-capable policy_mapping_fn definition via providing a callable class here.
            policy_mapping_fn:
                type: ray.rllib.examples.multi_agent_and_self_play.policy_mapping_fn.PolicyMappingFn