ppo-team-rock-sampling:
    env: envs.rock_sampling.team_problem.RockSampling
    run: PPO
    stop:
        timesteps_total: 300000
    config:
        # Works for both torch and tf.
        framework: torch
        lambda: 0.95
        gamma: 0.99
        lr: 0.0001
        kl_coeff: 0.5
        clip_rewards: False
        clip_param: 0.1
        vf_clip_param: 10.0
        entropy_coeff: 0.01
        train_batch_size: 5000
        rollout_fragment_length: 100
        sgd_minibatch_size: 500
        num_sgd_iter: 10
        num_envs_per_worker: 5
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        model:
            vf_share_layers: true